import { AppProvider } from '@luxfi/ui';
import { createRouter, RouterProvider } from '@tanstack/react-router';
import React from 'react';
import { createRoot } from 'react-dom/client';

import { routeTree } from './routeTree.gen';

// TanStack Router reads the file-based route tree auto-generated by the
// Vite plugin from src/routes/**. Strict types for every route out of the box.
const router = createRouter({ routeTree });

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

const rootEl = document.getElementById('root');
if (!rootEl) throw new Error('root element not found');

createRoot(rootEl).render(
  <React.StrictMode>
    <AppProvider>
      <RouterProvider router={ router } />
    </AppProvider>
  </React.StrictMode>,
);
