package main

import (
	"strings"
	"testing"
)

func TestPascalCase(t *testing.T) {
	tests := []struct {
		in, want string
	}{
		{"tasks", "Tasks"},
		{"user_roles", "UserRoles"},
		{"my-items", "MyItems"},
		{"users", "Users"},
		{"_superusers", "Superusers"},
		{"abc", "Abc"},
	}
	for _, tt := range tests {
		got := pascalCase(tt.in)
		if got != tt.want {
			t.Errorf("pascalCase(%q) = %q, want %q", tt.in, got, tt.want)
		}
	}
}

func TestSelectType(t *testing.T) {
	tests := []struct {
		name string
		f    field
		want string
	}{
		{
			name: "single select with values",
			f:    field{Type: "select", Values: []string{"active", "done"}, MaxSelect: 0},
			want: "'active' | 'done'",
		},
		{
			name: "multi select with values",
			f:    field{Type: "select", Values: []string{"a", "b", "c"}, MaxSelect: 3},
			want: "('a' | 'b' | 'c')[]",
		},
		{
			name: "single select no values",
			f:    field{Type: "select", Values: nil, MaxSelect: 0},
			want: "string",
		},
		{
			name: "multi select no values",
			f:    field{Type: "select", Values: nil, MaxSelect: 2},
			want: "string[]",
		},
		{
			name: "value with apostrophe",
			f:    field{Type: "select", Values: []string{"it's"}, MaxSelect: 0},
			want: "'it\\'s'",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := selectType(tt.f)
			if got != tt.want {
				t.Errorf("selectType() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestFieldToTS(t *testing.T) {
	idToName := map[string]string{
		"col_users": "users",
		"col_tags":  "tags",
	}

	tests := []struct {
		name    string
		f       field
		wantTS  string
		wantCmt string
	}{
		{"text", field{Type: "text"}, "string", ""},
		{"email", field{Type: "email"}, "string", ""},
		{"url", field{Type: "url"}, "string", ""},
		{"editor", field{Type: "editor"}, "string", ""},
		{"number", field{Type: "number"}, "number", ""},
		{"bool", field{Type: "bool"}, "boolean", ""},
		{"date", field{Type: "date"}, "string", ""},
		{"autodate", field{Type: "autodate"}, "string", ""},
		{"json", field{Type: "json"}, "unknown", ""},
		{"geoPoint", field{Type: "geoPoint"}, "{ lon: number; lat: number }", ""},
		{"password", field{Type: "password"}, "string", ""},
		{"file single", field{Type: "file", MaxSelect: 0}, "string", ""},
		{"file multi", field{Type: "file", MaxSelect: 3}, "string[]", ""},
		{"relation single", field{Type: "relation", CollectionID: "col_users", MaxSelect: 0}, "string", "relation -> users"},
		{"relation multi", field{Type: "relation", CollectionID: "col_tags", MaxSelect: 5}, "string[]", "relation -> tags"},
		{"relation unknown", field{Type: "relation", CollectionID: "unknown_id"}, "string", "relation -> unknown_id"},
		{"select", field{Type: "select", Values: []string{"a", "b"}}, "'a' | 'b'", ""},
		{"unknown type", field{Type: "foobar"}, "unknown", "unhandled type: foobar"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gotTS, gotCmt := fieldToTS(tt.f, idToName)
			if gotTS != tt.wantTS {
				t.Errorf("fieldToTS().ts = %q, want %q", gotTS, tt.wantTS)
			}
			if gotCmt != tt.wantCmt {
				t.Errorf("fieldToTS().comment = %q, want %q", gotCmt, tt.wantCmt)
			}
		})
	}
}

func TestGenerate(t *testing.T) {
	idToName := map[string]string{
		"col_users": "users",
	}

	collections := []collection{
		{
			ID:   "col_tasks",
			Name: "tasks",
			Type: "base",
			Fields: []field{
				{Name: "id", Type: "text", System: true},
				{Name: "title", Type: "text"},
				{Name: "status", Type: "select", Values: []string{"active", "done"}},
				{Name: "assignee", Type: "relation", CollectionID: "col_users"},
				{Name: "secret", Type: "text", Hidden: true},
				{Name: "created", Type: "autodate"},
				{Name: "updated", Type: "autodate"},
			},
		},
		{
			ID:   "col_users",
			Name: "users",
			Type: "auth",
			Fields: []field{
				{Name: "id", Type: "text", System: true},
				{Name: "email", Type: "email"},
				{Name: "name", Type: "text"},
				{Name: "avatar", Type: "file"},
				{Name: "verified", Type: "bool"},
				{Name: "created", Type: "autodate"},
				{Name: "updated", Type: "autodate"},
			},
		},
	}

	got := generate(collections, idToName)

	// Check header
	if !strings.Contains(got, "Auto-generated by base typegen") {
		t.Error("missing header comment")
	}

	// Check Tasks interface
	if !strings.Contains(got, "export interface Tasks {") {
		t.Error("missing Tasks interface")
	}
	if !strings.Contains(got, "  title: string") {
		t.Error("missing title field")
	}
	if !strings.Contains(got, "  status: 'active' | 'done'") {
		t.Error("missing status select union type")
	}
	if !strings.Contains(got, "  assignee: string  // relation -> users") {
		t.Error("missing assignee relation with comment")
	}

	// Hidden fields should be excluded
	if strings.Contains(got, "secret") {
		t.Error("hidden field 'secret' should not appear in output")
	}

	// Check Users interface
	if !strings.Contains(got, "export interface Users {") {
		t.Error("missing Users interface")
	}
	if !strings.Contains(got, "  verified: boolean") {
		t.Error("missing verified bool field")
	}

	// Check Collections map
	if !strings.Contains(got, "export type Collections = {") {
		t.Error("missing Collections type map")
	}
	if !strings.Contains(got, "  tasks: Tasks") {
		t.Error("missing tasks entry in Collections map")
	}
	if !strings.Contains(got, "  users: Users") {
		t.Error("missing users entry in Collections map")
	}
}
